apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
  namespace: todoapp
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
  type: NodePort