apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todoapp.fullname" . }}-postgres-config
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgresql.database }}
  POSTGRES_USER: {{ .Values.postgresql.username }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todoapp.fullname" . }}-postgres-secret
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todoapp.fullname" . }}-backend-config
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.service.backend.port }}"
  DB_HOST: {{ include "todoapp.fullname" . }}-postgres
  DB_PORT: "{{ .Values.service.postgres.port }}"
  DB_NAME: {{ .Values.postgresql.database }}
  DB_USER: {{ .Values.postgresql.username }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todoapp.fullname" . }}-backend-secret
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.password | b64enc }}