apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "todoapp.fullname" . }}-ingress
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "todoapp.fullname" $ }}-frontend
                port:
                  number: {{ $.Values.service.frontend.port }}
          {{- end }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "todoapp.fullname" $ }}-backend
                port:
                  number: {{ $.Values.service.backend.port }}
    {{- end }}